# require(devtools)
# install.packages("Rmosek", type="source", repos="http://download.mosek.com/R/7")
# require(Rmosek)
# install_github("cran/REBayes")
# require(REBayes)
# install_github("stephens999/ashr")
require(ashr)
require(REBayes)
lik <- read.table('data.txt')
prior <- scan('prior.txt')
pi.init <- scan('init.txt')
res1 <- mixEM(lik, prior, pi.init)
lapply(res1, write, "EM.res", append = T, ncolumns = 1000)
res2 <- mixIP(lik, prior, pi.init)
lapply(res2, write, "COP.res", append = T, ncolumns = 1000)
