geno: data/list_genotypes.txt
scoord: data/snp_coords.bed.gz
exp: data/list_phenotypes.txt
gcoord: data/gene_coords.bed.gz
anchor: TSS
cis: 5
lik: normal
analys: join
qnorm: 1
maf: 0.01
covar: data/list_covariates.txt
gridL: data/grid_phi2_oma2_general.txt.gz
gridS: data/grid_phi2_oma2_with-configs.txt.gz
priorM: data/prior-matrix*.txt.gz
gridM: data/matrix-scalars.txt.gz
bfs: customized
error: hybrid
fiterr: 0.5
nperm: 100
seed: 10086
trick: 0
tricut: 10
permsep: 0
pbf: all
maxbf: 0
thread: 4
snp:
sbgrp: [s1, s2, s3]
wrtsize: 5
verbose: 1