from OmicsBMA.pyeqtlbma import *
from OmicsBMA.core import *
configfile: "config.yaml"

rule bf:
  threads: config['thread']
  run:
    sstats = {'dat':{'dat':[[]]}}
    params = convert_data(config, "dict")
    exe = eQtlBma()
    exe.eqtlbma_bf(params["string"], params["int"], params["float"], sstats, params["vectors"])
    res = convert_data(exe.GetSstats(), "ddm")
    print(res)
