from OmicsBMA.pyeqtlbma import *
configfile: "config.yaml"

rule bf:
  run:
    param_i = {}
    param_s = {}
    param_f = {}
    param_vs = {}
    sstats = {'dat':{'dat':[[]]}}
    for k, val in list(config.items()):
        if type(val) == str:
            param_s[k] = val
        elif type(val) == float:
            param_f[k] = val
        elif type(val) == list:
            param_vs[k] = val
        elif type(val) == int:
            param_i[k] = val
        else:
            pass
    eqtlbma_bf(param_s, param_i, param_f, sstats, param_vs)
