from OmicsBMA.pyeqtlbma import *
from OmicsBMA.core import *
configfile: "config.yaml"

rule bf:
  threads:
    config['thread']
  run:
    sstats = None
    params = convert_data(config)
    exe = eQtlBma()
    exe.eqtlbma_bf(params["string"], params["int"], params["float"], params["vectors"],
                   {'':{'':[[]]}} if sstats is None else sstats)
    res = (convert_data(exe.GetSstats(), "ddm"),
           convert_data(exe.GetSstatsRownames(), "ddm"),
           convert_data(exe.GetSepPermPvals(), "dm"),
           convert_data(exe.GetSepPermPvalsRownames(), "dm"),
           exe.GetJoinPermPvals(),
           exe.GetJoinPermPvalsRownames(),
           convert_data(exe.GetAbfs(), "dm"),
           convert_data(exe.GetAbfsNames(), "dm")
           )
    print(res)
