configfile: "config.yaml"

rule doc_home:
  input:
    config["doc-home"].split()[0]
  output:
    "../../README.md"
  shell:
    "{config[md]} {input} -o {output}"

rule all:
  input: rules.doc_home.output
