configfile: "config.yaml"

rule home:
  input:
    "home.notes", "sidebar-development.notes"
  output:
    "../README.md",
    "wiki/development/start.txt",
    "wiki/development/sidebar.txt"
  shell:
    '''
    {config[md]} {input[0]} -o {output[0]};
    {config[wk]} {input[0]} -o {output[1]} --compact_toc
    {config[wk]} {input[1]} -o {output[2]} --compact_toc
    '''

rule doc:
  input:
    "doc.notes"
  output:
    "README.md"
  shell:
    "{config[md]} {input} -o {output}"

rule todo:
  input:
    "TODO.notes"
  output:
    "wiki/development/todo.txt"
  shell:
    '''
    {config[wk]} {input} -o {output}
    '''

rule src:
  input:
    "src.notes",
    "TODO.notes"
  output:
    "../src/README.md"
  shell:
    "{config[md]} {input} -o {output}"


rule src_internal_pyeqtlbma:
  input:
    "internal-pyeqtlbma.notes"
  output:
    "../src/internal/pyeqtlbma/README.md",
    "wiki/development/internal/pyeqtlbma.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc
    '''

rule src_external:
  input:
    "external.notes"
  output:
    "../src/external/README.md",
    "wiki/development/external.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc
    '''

rule src_internal:
  input:
    "internal.notes"
  output:
    "../src/internal/README.md",
    "wiki/development/internal.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc
    '''

rule bar1:
  input: "sidebar.notes"
  output: "wiki/sidebar.txt"
  shell: "{config[wk]} {input} -o {output} --compact_toc"

rule all:
  input:
    rules.home.output, rules.src_internal_pyeqtlbma.output,
    rules.src_external.output, rules.src_internal.output,
    rules.doc.output, rules.src.output, rules.todo.output,
    rules.bar1.output
  shell: "rsync -av --include='*/' --include='*.txt' --exclude='*' --prune-empty-dirs --delete --delete-excluded --chmod=g+w wiki/ {config[user]}@{config[path]}"
