configfile: "config.yaml"

rule home:
  input:
    "home.notes", "sidebar-development.notes"
  output:
    "../README.md",
    "wiki/development/start.txt",
    "wiki/development/sidebar.txt"
  shell:
    '''
    {config[md]} {input[0]} -o {output[0]};
    {config[wk]} {input[0]} -o {output[1]} --compact_toc
    {config[wk]} {input[1]} -o {output[2]} --compact_toc
    '''

rule doc:
  input:
    "doc.notes"
  output:
    "README.md"
  shell:
    "{config[md]} {input} -o {output}"

rule todo:
  input:
    "TODO.notes"
  output:
    "wiki/development/todo.txt"
  shell:
    '''
    {config[wk]} {input} -o {output}
    '''

rule src:
  input:
    "src.notes",
    "TODO.notes"
  output:
    "../src/README.md"
  shell:
    "{config[md]} {input} -o {output}"


rule src_internal_pyeqtlbma:
  input:
    "internal-pyeqtlbma.notes"
  output:
    "../src/internal/pyeqtlbma/README.md",
    "wiki/development/internal/pyeqtlbma.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc --stamps time git-version
    '''

rule src_external:
  input:
    "external.notes"
  output:
    "../src/external/README.md",
    "wiki/development/external.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc
    '''

rule src_internal:
  input:
    "internal.notes"
  output:
    "../src/internal/README.md",
    "wiki/development/internal.txt"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    {config[wk]} {input} -o {output[1]} --compact_toc
    '''

rule extra_scopt:
  input:
    "extra-sep-convopt.notes"
  output:
    "wiki/development/scopt-implementation.txt"
  shell:
    '''
    {config[wk]} {input} -o {output} --compact_toc --stamps time git-version
    '''

rule extra_mosek:
  input:
    "extra-mosek.notes"
  output:
    "wiki/development/installation-mosek.txt"
  shell:
    '''
    {config[wk]} {input} -o {output} --compact_toc
    '''

rule admin:
  input:
    "admin.notes"
  output:
    "../src/admin/README.md"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    '''

rule unit_test_mk:
  input:
    "unit-tests-mk.notes"
  output:
    "../src/unit-tests/mosek-kwdual/README.md"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    '''

rule unit_test_interface:
  input:
    "unit-tests-interface.notes"
  output:
    "../src/unit-tests/pyeqtlbma-interface/README.md"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    '''

rule unit_test_bf:
  input:
    "unit-tests-bf.notes"
  output:
    "../src/unit-tests/test-association/README.md"
  shell:
    '''
    {config[md]} {input} -o {output[0]};
    '''

rule bar1:
  input: "sidebar.notes"
  output: "wiki/sidebar.txt"
  shell: "{config[wk]} {input} -o {output} --compact_toc"

rule all:
  input:
    rules.home.output, rules.src_internal_pyeqtlbma.output,
    rules.src_external.output, rules.src_internal.output,
    rules.doc.output, rules.src.output, rules.todo.output,
    rules.bar1.output, rules.extra_scopt.output,
    rules.extra_mosek.output, rules.admin.output,
    rules.unit_test_mk.output, rules.unit_test_interface.output,
    rules.unit_test_bf.output
  shell: "rsync -av --include='*/' --include='*.txt' --exclude='*' --prune-empty-dirs --delete --delete-excluded --chmod=g+w wiki/ {config[user]}@{config[path]}"
