__doc__ = '''
setup file for pyeqtlbma
Note:
- for rules gsl and deepdish, to update the installation, the corresponding log files have to be removed before rebuilt
'''

rule help:
  shell: "snakemake -l"

rule gsl:
  output: "../external/gsl/config.log"
  shell: '''cd ../external/gsl; ./configure CFLAGS="-O3 -fPIC" --prefix=`pwd`; make; make install; cd -'''

rule swig:
  input:
    h = "pyeqtlbma/pyeqtlbma.hpp",
    c = "pyeqtlbma/pyeqtlbma.cpp",
    i = "pyeqtlbma/pyeqtlbma.i",
  output:
    cxx = "pyeqtlbma/pyeqtlbma_wrap.cxx",
    py = "pyeqtlbma/__init__.py"
  params:
    swig_opts = "-c++ -python -O -shadow -keyword -w-511 -w-509",
    swig_interface = "pyeqtlbma/pyeqtlbma.py"
  shell:
    "swig {params.swig_opts} -o {output.cxx} {input.i}; mv {params.swig_interface} {output.py}"

rule deepdish:
  input: "../external/deepdish/setup.py"
  output: "../external/deepdish/deepdish.log"
  shell: "cd ../external/deepdish; python setup.py install > deepdish.log; cd -"

rule utils:
  output: "pyper.py", "utils.py"
  run:
    for item in output:
        shell('wget https://raw.githubusercontent.com/gaow/utils/master/{}'.format(item))

rule install:
  input:
    rules.gsl.output,
    rules.swig.output,
    rules.deepdish.output,
    rules.utils.output
  output:
    touch("build.done")
  shell: "python setup.py install"

rule test:
  shell: "echo TODO ..."

rule clean:
  shell: "rm -rf build.done dist *.egg-info"

rule purge:
  shell: "git clean -df"

rule all:
  input:
    "build.done"
  shell: "snakemake clean"
