# Association testing
geno: data/list_genotypes.txt
scoord: data/snp_coords.bed.gz
exp: data/list_phenotypes.txt
gcoord: data/gene_coords.bed.gz
covar: data/list_covariates.txt
out_avg: 1
sumstats:
anchor: TSS
cis: 5
lik: normal
analys: join
qnorm: 1
maf: 0.01
priors: data/priors.h5
bfs: sin, customized
error: hybrid
fiterr: 0.5
nperm: 100
seed: 10086
trick: 0
tricut: 10
permsep: 0
pbf: all
maxbf: 0
thread: 8
snp:
sbgrp: s1, s2, s3
verbose: 1
output: stamp(output/test_association.h5)
# Mixture model fitting
