from OmicsBMA.core import test_association

configfile: "config.yaml"

rule test_association:
  threads:
    config['thread']
  output:
    touch("test_association.done")
  run:
    test_association(config)

rule all:
  input:
    "test_association.done"

rule clean:
  shell: "rm -f *.done"
