from OmicsBMA.core import test_association, fit_hm

configfile: "config.yaml"

rule test_association:
  threads:
    config['thread']
  output:
    touch("test_association.done")
  run:
    test_association(config)

rule fit_hm:
  threads:
    config['thread']
  output:
    touch("fit_hm.done")
  run:
    fit_hm(config)

rule all:
  input:
    "test_association.done", "fit_hm.done"

rule clean:
  shell: "rm -f *.done"
